security:
    # Gestion du hashage des mots de passe
    password_hashers:
        App\Entity\Clients:
            algorithm: auto

    # Chargement des utilisateurs (depuis la table Clients)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Clients
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Authentification par formulaire de login
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /cakes
                enable_csrf: true

            logout:
                path: app_logout       # correspond à ta route /logout
                target: /cakes         # redirection après logout

            # Remember me (facultatif)
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                path: /
            custom_authenticator: App\Security\LoginFormAuthenticator

    access_control:
        # Exemple : protège la partie admin
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Les autres routes accessibles sans être connecté
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            App\Entity\Clients:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
